[2022-03-21 21:49:06,273] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: BQ_dag.external_task_sensor manual__2022-03-21T21:49:04.719912+00:00 [queued]>
[2022-03-21 21:49:06,280] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: BQ_dag.external_task_sensor manual__2022-03-21T21:49:04.719912+00:00 [queued]>
[2022-03-21 21:49:06,280] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 21:49:06,280] {taskinstance.py:1244} INFO - Starting attempt 1 of 3
[2022-03-21 21:49:06,281] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 21:49:06,287] {taskinstance.py:1264} INFO - Executing <Task(ExternalTaskSensor): external_task_sensor> on 2022-03-21 21:49:04.719912+00:00
[2022-03-21 21:49:06,292] {standard_task_runner.py:52} INFO - Started process 2970 to run task
[2022-03-21 21:49:06,294] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'BQ_dag', 'external_task_sensor', 'manual__2022-03-21T21:49:04.719912+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/extract_load_dags.py', '--cfg-path', '/tmp/tmpq0c6058v', '--error-file', '/tmp/tmplwiatvts']
[2022-03-21 21:49:06,295] {standard_task_runner.py:77} INFO - Job 44: Subtask external_task_sensor
[2022-03-21 21:49:06,410] {logging_mixin.py:109} INFO - Running <TaskInstance: BQ_dag.external_task_sensor manual__2022-03-21T21:49:04.719912+00:00 [running]> on host 7fae4c5ec6da
[2022-03-21 21:49:06,453] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BQ_dag
AIRFLOW_CTX_TASK_ID=external_task_sensor
AIRFLOW_CTX_EXECUTION_DATE=2022-03-21T21:49:04.719912+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-21T21:49:04.719912+00:00
[2022-03-21 21:49:06,454] {external_task.py:169} INFO - Poking for tasks ['remove_dataset_task'] in dag EL_dag on 2022-03-21T21:49:04.719912+00:00 ... 
[2022-03-21 21:50:06,503] {external_task.py:169} INFO - Poking for tasks ['remove_dataset_task'] in dag EL_dag on 2022-03-21T21:49:04.719912+00:00 ... 
[2022-03-21 21:51:06,575] {external_task.py:169} INFO - Poking for tasks ['remove_dataset_task'] in dag EL_dag on 2022-03-21T21:49:04.719912+00:00 ... 
[2022-03-21 21:52:06,650] {external_task.py:169} INFO - Poking for tasks ['remove_dataset_task'] in dag EL_dag on 2022-03-21T21:49:04.719912+00:00 ... 
[2022-03-21 21:52:06,660] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/sensors/base.py", line 242, in execute
    raise AirflowSensorTimeout(f"Snap. Time is OUT. DAG id: {log_dag_id}")
airflow.exceptions.AirflowSensorTimeout: Snap. Time is OUT. DAG id: BQ_dag
[2022-03-21 21:52:06,671] {taskinstance.py:1272} INFO - Immediate failure requested. Marking task as FAILED. dag_id=BQ_dag, task_id=external_task_sensor, execution_date=20220321T214904, start_date=20220321T214906, end_date=20220321T215206
[2022-03-21 21:52:06,681] {standard_task_runner.py:89} ERROR - Failed to execute job 44 for task external_task_sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/sensors/base.py", line 242, in execute
    raise AirflowSensorTimeout(f"Snap. Time is OUT. DAG id: {log_dag_id}")
airflow.exceptions.AirflowSensorTimeout: Snap. Time is OUT. DAG id: BQ_dag
[2022-03-21 21:52:06,708] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-21 21:52:06,740] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
