[2022-03-21 21:24:27,994] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: BQ_dag.external_task_sensor scheduled__2022-03-21T21:24:06.951066+00:00 [queued]>
[2022-03-21 21:24:28,001] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: BQ_dag.external_task_sensor scheduled__2022-03-21T21:24:06.951066+00:00 [queued]>
[2022-03-21 21:24:28,001] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 21:24:28,001] {taskinstance.py:1244} INFO - Starting attempt 1 of 3
[2022-03-21 21:24:28,001] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 21:24:28,008] {taskinstance.py:1264} INFO - Executing <Task(ExternalTaskSensor): external_task_sensor> on 2022-03-21 21:24:06.951066+00:00
[2022-03-21 21:24:28,012] {standard_task_runner.py:52} INFO - Started process 1531 to run task
[2022-03-21 21:24:28,015] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'BQ_dag', 'external_task_sensor', 'scheduled__2022-03-21T21:24:06.951066+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/extract_load_dags.py', '--cfg-path', '/tmp/tmpz1tabsyr', '--error-file', '/tmp/tmp0wiwzsv8']
[2022-03-21 21:24:28,016] {standard_task_runner.py:77} INFO - Job 22: Subtask external_task_sensor
[2022-03-21 21:24:28,131] {logging_mixin.py:109} INFO - Running <TaskInstance: BQ_dag.external_task_sensor scheduled__2022-03-21T21:24:06.951066+00:00 [running]> on host 7fae4c5ec6da
[2022-03-21 21:24:28,178] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BQ_dag
AIRFLOW_CTX_TASK_ID=external_task_sensor
AIRFLOW_CTX_EXECUTION_DATE=2022-03-21T21:24:06.951066+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-21T21:24:06.951066+00:00
[2022-03-21 21:24:28,178] {external_task.py:169} INFO - Poking for tasks ['remove_dataset_task'] in dag EL_dag on 2022-03-21T21:24:06.951066+00:00 ... 
[2022-03-21 21:25:28,248] {external_task.py:169} INFO - Poking for tasks ['remove_dataset_task'] in dag EL_dag on 2022-03-21T21:24:06.951066+00:00 ... 
[2022-03-21 21:26:28,316] {external_task.py:169} INFO - Poking for tasks ['remove_dataset_task'] in dag EL_dag on 2022-03-21T21:24:06.951066+00:00 ... 
[2022-03-21 21:27:28,386] {external_task.py:169} INFO - Poking for tasks ['remove_dataset_task'] in dag EL_dag on 2022-03-21T21:24:06.951066+00:00 ... 
[2022-03-21 21:27:28,396] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/sensors/base.py", line 242, in execute
    raise AirflowSensorTimeout(f"Snap. Time is OUT. DAG id: {log_dag_id}")
airflow.exceptions.AirflowSensorTimeout: Snap. Time is OUT. DAG id: BQ_dag
[2022-03-21 21:27:28,408] {taskinstance.py:1272} INFO - Immediate failure requested. Marking task as FAILED. dag_id=BQ_dag, task_id=external_task_sensor, execution_date=20220321T212406, start_date=20220321T212427, end_date=20220321T212728
[2022-03-21 21:27:28,416] {standard_task_runner.py:89} ERROR - Failed to execute job 22 for task external_task_sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/sensors/base.py", line 242, in execute
    raise AirflowSensorTimeout(f"Snap. Time is OUT. DAG id: {log_dag_id}")
airflow.exceptions.AirflowSensorTimeout: Snap. Time is OUT. DAG id: BQ_dag
[2022-03-21 21:27:28,429] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-21 21:27:28,461] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
