[2022-03-21 10:55:24,180] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: EL_dag.extract_task scheduled__2012-02-02T01:00:00+00:00 [queued]>
[2022-03-21 10:55:24,188] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: EL_dag.extract_task scheduled__2012-02-02T01:00:00+00:00 [queued]>
[2022-03-21 10:55:24,188] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 10:55:24,188] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-03-21 10:55:24,188] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 10:55:24,195] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): extract_task> on 2012-02-02 01:00:00+00:00
[2022-03-21 10:55:24,199] {standard_task_runner.py:52} INFO - Started process 436 to run task
[2022-03-21 10:55:24,202] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'EL_dag', 'extract_task', 'scheduled__2012-02-02T01:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/extract_load_dags.py', '--cfg-path', '/tmp/tmp30rjh3e2', '--error-file', '/tmp/tmp9wt4mkxy']
[2022-03-21 10:55:24,202] {standard_task_runner.py:77} INFO - Job 7: Subtask extract_task
[2022-03-21 10:55:24,255] {logging_mixin.py:109} INFO - Running <TaskInstance: EL_dag.extract_task scheduled__2012-02-02T01:00:00+00:00 [running]> on host 5908b9c456cd
[2022-03-21 10:55:24,363] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.9/site-packages/airflow/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-03-21 10:55:24,384] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=EL_dag
AIRFLOW_CTX_TASK_ID=extract_task
AIRFLOW_CTX_EXECUTION_DATE=2012-02-02T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2012-02-02T01:00:00+00:00
[2022-03-21 10:55:24,384] {logging_mixin.py:109} INFO - 02 2012
[2022-03-21 10:55:39,480] {logging_mixin.py:109} INFO - the response is  200
[2022-03-21 10:55:39,480] {logging_mixin.py:109} INFO - here.........
[2022-03-21 10:55:39,516] {logging_mixin.py:109} INFO -   invoice_line_no                     date  ... sale_liters sale_gallons
0    S04067600021  2012-02-14T00:00:00.000  ...        1.50         0.40
1    S04203600001  2012-02-22T00:00:00.000  ...       10.50         2.77
2    S04225000073  2012-02-22T00:00:00.000  ...        2.25         0.59
3    S03951800056  2012-02-07T00:00:00.000  ...       24.00         6.34
4    S04118500006  2012-02-16T00:00:00.000  ...        9.00         2.38

[5 rows x 24 columns]
[2022-03-21 10:55:39,536] {logging_mixin.py:109} INFO - Data saved..........
[2022-03-21 10:55:39,537] {python.py:175} INFO - Done. Returned value was: None
[2022-03-21 10:55:39,548] {taskinstance.py:1272} INFO - Marking task as SUCCESS. dag_id=EL_dag, task_id=extract_task, execution_date=20120202T010000, start_date=20220321T105524, end_date=20220321T105539
[2022-03-21 10:55:39,564] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-21 10:55:39,650] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-21 21:24:08,420] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: EL_dag.extract_task scheduled__2012-02-02T01:00:00+00:00 [queued]>
[2022-03-21 21:24:09,112] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: EL_dag.extract_task scheduled__2012-02-02T01:00:00+00:00 [queued]>
[2022-03-21 21:24:09,112] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 21:24:09,112] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-03-21 21:24:09,113] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 21:24:09,127] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): extract_task> on 2012-02-02 01:00:00+00:00
[2022-03-21 21:24:13,462] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'EL_dag', 'extract_task', 'scheduled__2012-02-02T01:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/extract_load_dags.py', '--cfg-path', '/tmp/tmpdcxwq7ix', '--error-file', '/tmp/tmpx959a047']
[2022-03-21 21:24:13,465] {standard_task_runner.py:77} INFO - Job 21: Subtask extract_task
[2022-03-21 21:24:10,597] {standard_task_runner.py:52} INFO - Started process 1512 to run task
[2022-03-21 21:24:18,316] {logging_mixin.py:109} INFO - Running <TaskInstance: EL_dag.extract_task scheduled__2012-02-02T01:00:00+00:00 [running]> on host 7fae4c5ec6da
[2022-03-21 21:24:18,343] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.9/site-packages/airflow/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-03-21 21:24:18,365] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=EL_dag
AIRFLOW_CTX_TASK_ID=extract_task
AIRFLOW_CTX_EXECUTION_DATE=2012-02-02T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2012-02-02T01:00:00+00:00
[2022-03-21 21:24:18,365] {logging_mixin.py:109} INFO - 02 2012
[2022-03-21 21:24:35,502] {logging_mixin.py:109} INFO - the response is  200
[2022-03-21 21:24:35,502] {logging_mixin.py:109} INFO - here.........
[2022-03-21 21:24:35,534] {logging_mixin.py:109} INFO -   invoice_line_no                     date  ... sale_gallons store_location
0    S04199100072  2012-02-21T00:00:00.000  ...         2.77           None
1    S04127600055  2012-02-16T00:00:00.000  ...         2.77           None
2    S04241700009  2012-02-23T00:00:00.000  ...         2.77           None
3    S04343000106  2012-02-29T00:00:00.000  ...         0.40           None
4    S03946700144  2012-02-07T00:00:00.000  ...         0.79           None

[5 rows x 24 columns]
[2022-03-21 21:24:35,545] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/iowa/airflow/dags/extract_load.py", line 28, in get_api_data
    df.to_parquet(f"../data/data_{year}-{month}.parquet",index=False)
  File "/usr/local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/frame.py", line 2677, in to_parquet
    return to_parquet(
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parquet.py", line 416, in to_parquet
    impl.write(
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parquet.py", line 175, in write
    path_or_handle, handles, kwargs["filesystem"] = _get_path_or_handle(
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parquet.py", line 101, in _get_path_or_handle
    handles = get_handle(
  File "/usr/local/lib/python3.9/site-packages/pandas/io/common.py", line 711, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '../data/data_2012-02.parquet'
[2022-03-21 21:24:35,559] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=EL_dag, task_id=extract_task, execution_date=20120202T010000, start_date=20220321T212409, end_date=20220321T212435
[2022-03-21 21:24:35,567] {standard_task_runner.py:89} ERROR - Failed to execute job 21 for task extract_task
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/iowa/airflow/dags/extract_load.py", line 28, in get_api_data
    df.to_parquet(f"../data/data_{year}-{month}.parquet",index=False)
  File "/usr/local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/frame.py", line 2677, in to_parquet
    return to_parquet(
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parquet.py", line 416, in to_parquet
    impl.write(
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parquet.py", line 175, in write
    path_or_handle, handles, kwargs["filesystem"] = _get_path_or_handle(
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parquet.py", line 101, in _get_path_or_handle
    handles = get_handle(
  File "/usr/local/lib/python3.9/site-packages/pandas/io/common.py", line 711, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '../data/data_2012-02.parquet'
[2022-03-21 21:24:35,588] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-21 21:24:35,617] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
