[2022-03-21 10:55:56,577] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: EL_dag.remove_dataset_task scheduled__2012-02-02T01:00:00+00:00 [queued]>
[2022-03-21 10:55:56,585] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: EL_dag.remove_dataset_task scheduled__2012-02-02T01:00:00+00:00 [queued]>
[2022-03-21 10:55:56,586] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 10:55:56,586] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-03-21 10:55:56,586] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 10:55:56,598] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): remove_dataset_task> on 2012-02-02 01:00:00+00:00
[2022-03-21 10:55:56,603] {standard_task_runner.py:52} INFO - Started process 498 to run task
[2022-03-21 10:55:56,606] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'EL_dag', 'remove_dataset_task', 'scheduled__2012-02-02T01:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/extract_load_dags.py', '--cfg-path', '/tmp/tmp8z6efdi0', '--error-file', '/tmp/tmpcjpdg35g']
[2022-03-21 10:55:56,607] {standard_task_runner.py:77} INFO - Job 9: Subtask remove_dataset_task
[2022-03-21 10:55:56,663] {logging_mixin.py:109} INFO - Running <TaskInstance: EL_dag.remove_dataset_task scheduled__2012-02-02T01:00:00+00:00 [running]> on host 5908b9c456cd
[2022-03-21 10:55:56,771] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.9/site-packages/airflow/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-03-21 10:55:56,792] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=EL_dag
AIRFLOW_CTX_TASK_ID=remove_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2012-02-02T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2012-02-02T01:00:00+00:00
[2022-03-21 10:55:56,792] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-21 10:55:56,792] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'rm ../data/data_2012-02.parquet ']
[2022-03-21 10:55:56,799] {subprocess.py:85} INFO - Output:
[2022-03-21 10:55:56,800] {subprocess.py:89} INFO - rm: cannot remove '../data/data_2012-02.parquet': No such file or directory
[2022-03-21 10:55:56,800] {subprocess.py:93} INFO - Command exited with return code 1
[2022-03-21 10:55:56,812] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/bash.py", line 187, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-03-21 10:55:56,816] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=EL_dag, task_id=remove_dataset_task, execution_date=20120202T010000, start_date=20220321T105556, end_date=20220321T105556
[2022-03-21 10:55:56,824] {standard_task_runner.py:89} ERROR - Failed to execute job 9 for task remove_dataset_task
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/bash.py", line 187, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-03-21 10:55:56,859] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-21 10:55:56,906] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-03-21 21:33:59,818] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: EL_dag.remove_dataset_task scheduled__2012-02-02T01:00:00+00:00 [queued]>
[2022-03-21 21:33:59,825] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: EL_dag.remove_dataset_task scheduled__2012-02-02T01:00:00+00:00 [queued]>
[2022-03-21 21:33:59,825] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 21:33:59,825] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-03-21 21:33:59,826] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 21:33:59,841] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): remove_dataset_task> on 2012-02-02 01:00:00+00:00
[2022-03-21 21:33:59,845] {standard_task_runner.py:52} INFO - Started process 2146 to run task
[2022-03-21 21:33:59,848] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'EL_dag', 'remove_dataset_task', 'scheduled__2012-02-02T01:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/extract_load_dags.py', '--cfg-path', '/tmp/tmpdkka9fpi', '--error-file', '/tmp/tmpuatq43n7']
[2022-03-21 21:33:59,849] {standard_task_runner.py:77} INFO - Job 36: Subtask remove_dataset_task
[2022-03-21 21:34:00,006] {logging_mixin.py:109} INFO - Running <TaskInstance: EL_dag.remove_dataset_task scheduled__2012-02-02T01:00:00+00:00 [running]> on host 7fae4c5ec6da
[2022-03-21 21:34:00,078] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.9/site-packages/airflow/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-03-21 21:34:00,108] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=EL_dag
AIRFLOW_CTX_TASK_ID=remove_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2012-02-02T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2012-02-02T01:00:00+00:00
[2022-03-21 21:34:00,109] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-21 21:34:00,109] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'rm /opt/iowa/data/data_2012-02.parquet ']
[2022-03-21 21:34:00,117] {subprocess.py:85} INFO - Output:
[2022-03-21 21:34:00,119] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-21 21:34:00,156] {taskinstance.py:1272} INFO - Marking task as SUCCESS. dag_id=EL_dag, task_id=remove_dataset_task, execution_date=20120202T010000, start_date=20220321T213359, end_date=20220321T213400
[2022-03-21 21:34:00,181] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-21 21:34:00,217] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
