[2022-03-21 11:01:50,144] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: EL_dag.remove_dataset_task scheduled__2012-01-02T01:00:00+00:00 [queued]>
[2022-03-21 11:01:50,151] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: EL_dag.remove_dataset_task scheduled__2012-01-02T01:00:00+00:00 [queued]>
[2022-03-21 11:01:50,151] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 11:01:50,151] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-03-21 11:01:50,152] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 11:01:50,158] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): remove_dataset_task> on 2012-01-02 01:00:00+00:00
[2022-03-21 11:01:50,161] {standard_task_runner.py:52} INFO - Started process 284 to run task
[2022-03-21 11:01:50,164] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'EL_dag', 'remove_dataset_task', 'scheduled__2012-01-02T01:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/extract_load_dags.py', '--cfg-path', '/tmp/tmpx9z_g8lm', '--error-file', '/tmp/tmpwmc3ns3s']
[2022-03-21 11:01:50,165] {standard_task_runner.py:77} INFO - Job 18: Subtask remove_dataset_task
[2022-03-21 11:01:50,211] {logging_mixin.py:109} INFO - Running <TaskInstance: EL_dag.remove_dataset_task scheduled__2012-01-02T01:00:00+00:00 [running]> on host 5908b9c456cd
[2022-03-21 11:01:50,302] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.9/site-packages/airflow/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-03-21 11:01:50,319] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=EL_dag
AIRFLOW_CTX_TASK_ID=remove_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2012-01-02T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2012-01-02T01:00:00+00:00
[2022-03-21 11:01:50,320] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-21 11:01:50,321] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'rm ../data/data_2012-01.parquet ']
[2022-03-21 11:01:50,327] {subprocess.py:85} INFO - Output:
[2022-03-21 11:01:50,328] {subprocess.py:89} INFO - rm: cannot remove '../data/data_2012-01.parquet': No such file or directory
[2022-03-21 11:01:50,328] {subprocess.py:93} INFO - Command exited with return code 1
[2022-03-21 11:01:50,340] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/bash.py", line 187, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-03-21 11:01:50,344] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=EL_dag, task_id=remove_dataset_task, execution_date=20120102T010000, start_date=20220321T110150, end_date=20220321T110150
[2022-03-21 11:01:50,352] {standard_task_runner.py:89} ERROR - Failed to execute job 18 for task remove_dataset_task
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/bash.py", line 187, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-03-21 11:01:50,377] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-21 11:01:50,402] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-03-21 21:33:53,714] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: EL_dag.remove_dataset_task scheduled__2012-01-02T01:00:00+00:00 [queued]>
[2022-03-21 21:33:53,721] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: EL_dag.remove_dataset_task scheduled__2012-01-02T01:00:00+00:00 [queued]>
[2022-03-21 21:33:53,721] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 21:33:53,721] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-03-21 21:33:53,722] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 21:33:53,730] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): remove_dataset_task> on 2012-01-02 01:00:00+00:00
[2022-03-21 21:33:53,733] {standard_task_runner.py:52} INFO - Started process 2112 to run task
[2022-03-21 21:33:53,736] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'EL_dag', 'remove_dataset_task', 'scheduled__2012-01-02T01:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/extract_load_dags.py', '--cfg-path', '/tmp/tmpjz6cd82x', '--error-file', '/tmp/tmpgyxg14ce']
[2022-03-21 21:33:53,737] {standard_task_runner.py:77} INFO - Job 34: Subtask remove_dataset_task
[2022-03-21 21:33:53,856] {logging_mixin.py:109} INFO - Running <TaskInstance: EL_dag.remove_dataset_task scheduled__2012-01-02T01:00:00+00:00 [running]> on host 7fae4c5ec6da
[2022-03-21 21:33:53,887] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.9/site-packages/airflow/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-03-21 21:33:53,910] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=EL_dag
AIRFLOW_CTX_TASK_ID=remove_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2012-01-02T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2012-01-02T01:00:00+00:00
[2022-03-21 21:33:53,911] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-21 21:33:53,911] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'rm /opt/iowa/data/data_2012-01.parquet ']
[2022-03-21 21:33:53,918] {subprocess.py:85} INFO - Output:
[2022-03-21 21:33:53,919] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-21 21:33:53,943] {taskinstance.py:1272} INFO - Marking task as SUCCESS. dag_id=EL_dag, task_id=remove_dataset_task, execution_date=20120102T010000, start_date=20220321T213353, end_date=20220321T213353
[2022-03-21 21:33:53,989] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-21 21:33:54,015] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
