[2022-03-23 19:14:12,957] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.iowa.staging_sales manual__2022-03-23T19:14:12.667416+00:00 [queued]>
[2022-03-23 19:14:12,964] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.iowa.staging_sales manual__2022-03-23T19:14:12.667416+00:00 [queued]>
[2022-03-23 19:14:12,964] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 19:14:12,964] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-23 19:14:12,964] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 19:14:12,975] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): model.iowa.staging_sales> on 2022-03-23 19:14:12.667416+00:00
[2022-03-23 19:14:12,977] {standard_task_runner.py:52} INFO - Started process 225 to run task
[2022-03-23 19:14:12,980] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag', 'model.iowa.staging_sales', 'manual__2022-03-23T19:14:12.667416+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/transform_dags.py', '--cfg-path', '/tmp/tmpqcvn3z_a', '--error-file', '/tmp/tmpqpg9cyuq']
[2022-03-23 19:14:12,980] {standard_task_runner.py:77} INFO - Job 99: Subtask model.iowa.staging_sales
[2022-03-23 19:14:13,031] {logging_mixin.py:109} INFO - Running <TaskInstance: dbt_dag.model.iowa.staging_sales manual__2022-03-23T19:14:12.667416+00:00 [running]> on host 7fae4c5ec6da
[2022-03-23 19:14:13,079] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=model.iowa.staging_sales
AIRFLOW_CTX_EXECUTION_DATE=2022-03-23T19:14:12.667416+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-23T19:14:12.667416+00:00
[2022-03-23 19:14:13,080] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-23 19:14:13,084] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n            cd /opt/iowa/dbt/iowa &&\n            dbt --no-write-json run --target prod --models staging_sales\n            ']
[2022-03-23 19:14:13,089] {subprocess.py:85} INFO - Output:
[2022-03-23 19:14:15,775] {subprocess.py:89} INFO - 19:14:15  Running with dbt=1.0.4
[2022-03-23 19:14:15,797] {subprocess.py:89} INFO - 19:14:15  Unable to do partial parsing because config vars, config profile, or config target have changed
[2022-03-23 19:14:16,402] {subprocess.py:89} INFO - 19:14:16  Found 1 model, 0 tests, 0 snapshots, 0 analyses, 188 macros, 0 operations, 0 seed files, 1 source, 0 exposures, 0 metrics
[2022-03-23 19:14:16,404] {subprocess.py:89} INFO - 19:14:16
[2022-03-23 19:14:22,435] {subprocess.py:89} INFO - 19:14:22  Concurrency: 4 threads (target='prod')
[2022-03-23 19:14:22,435] {subprocess.py:89} INFO - 19:14:22
[2022-03-23 19:14:22,439] {subprocess.py:89} INFO - 19:14:22  1 of 1 START view model iowa_prod.staging_sales................................. [RUN]
[2022-03-23 19:14:27,146] {subprocess.py:89} INFO - 19:14:27  1 of 1 ERROR creating view model iowa_prod.staging_sales........................ [ERROR in 4.71s]
[2022-03-23 19:14:27,148] {subprocess.py:89} INFO - 19:14:27
[2022-03-23 19:14:27,149] {subprocess.py:89} INFO - 19:14:27  Finished running 1 view model in 10.74s.
[2022-03-23 19:14:27,149] {subprocess.py:89} INFO - 19:14:27
[2022-03-23 19:14:27,150] {subprocess.py:89} INFO - 19:14:27  Completed with 1 error and 0 warnings:
[2022-03-23 19:14:27,150] {subprocess.py:89} INFO - 19:14:27
[2022-03-23 19:14:27,151] {subprocess.py:89} INFO - 19:14:27  Database Error in model staging_sales (models/staging/staging_sales.sql)
[2022-03-23 19:14:27,151] {subprocess.py:89} INFO - 19:14:27    Invalid project ID 'iowa_project_de'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.
[2022-03-23 19:14:27,151] {subprocess.py:89} INFO - 19:14:27    compiled SQL at target/run/iowa/models/staging/staging_sales.sql
[2022-03-23 19:14:27,152] {subprocess.py:89} INFO - 19:14:27
[2022-03-23 19:14:27,152] {subprocess.py:89} INFO - 19:14:27  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2022-03-23 19:14:32,039] {subprocess.py:93} INFO - Command exited with return code 1
[2022-03-23 19:14:32,051] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/bash.py", line 187, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-03-23 19:14:32,062] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=dbt_dag, task_id=model.iowa.staging_sales, execution_date=20220323T191412, start_date=20220323T191412, end_date=20220323T191432
[2022-03-23 19:14:32,077] {standard_task_runner.py:89} ERROR - Failed to execute job 99 for task model.iowa.staging_sales
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/bash.py", line 187, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-03-23 19:14:32,095] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-23 19:14:32,123] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
