[2022-03-24 15:40:33,038] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.iowa.staging_sales manual__2022-03-24T15:40:32.745573+00:00 [queued]>
[2022-03-24 15:40:33,044] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.iowa.staging_sales manual__2022-03-24T15:40:32.745573+00:00 [queued]>
[2022-03-24 15:40:33,044] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-24 15:40:33,044] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-24 15:40:33,044] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-24 15:40:33,052] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): model.iowa.staging_sales> on 2022-03-24 15:40:32.745573+00:00
[2022-03-24 15:40:33,054] {standard_task_runner.py:52} INFO - Started process 215 to run task
[2022-03-24 15:40:33,056] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag', 'model.iowa.staging_sales', 'manual__2022-03-24T15:40:32.745573+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/transform_dags.py', '--cfg-path', '/tmp/tmp5c07_335', '--error-file', '/tmp/tmpvdojpfp6']
[2022-03-24 15:40:33,057] {standard_task_runner.py:77} INFO - Job 172: Subtask model.iowa.staging_sales
[2022-03-24 15:40:33,111] {logging_mixin.py:109} INFO - Running <TaskInstance: dbt_dag.model.iowa.staging_sales manual__2022-03-24T15:40:32.745573+00:00 [running]> on host a91ac75a8f43
[2022-03-24 15:40:33,171] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=model.iowa.staging_sales
AIRFLOW_CTX_EXECUTION_DATE=2022-03-24T15:40:32.745573+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-24T15:40:32.745573+00:00
[2022-03-24 15:40:33,171] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-24 15:40:33,172] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n            cd /opt/iowa/dbt/iowa &&\n            dbt --no-write-json run --target dev --models staging_sales\n            ']
[2022-03-24 15:40:33,175] {subprocess.py:85} INFO - Output:
[2022-03-24 15:40:35,848] {subprocess.py:89} INFO - 15:40:35  Running with dbt=1.0.4
[2022-03-24 15:40:35,872] {subprocess.py:89} INFO - 15:40:35  Unable to do partial parsing because config vars, config profile, or config target have changed
[2022-03-24 15:40:36,530] {subprocess.py:89} INFO - 15:40:36  Found 8 models, 2 tests, 0 snapshots, 0 analyses, 188 macros, 0 operations, 0 seed files, 1 source, 0 exposures, 0 metrics
[2022-03-24 15:40:36,531] {subprocess.py:89} INFO - 15:40:36
[2022-03-24 15:40:41,733] {subprocess.py:89} INFO - 15:40:41  Concurrency: 4 threads (target='dev')
[2022-03-24 15:40:41,733] {subprocess.py:89} INFO - 15:40:41
[2022-03-24 15:40:41,738] {subprocess.py:89} INFO - 15:40:41  1 of 1 START view model iowa_staging.staging_sales.............................. [RUN]
[2022-03-24 15:40:47,558] {subprocess.py:89} INFO - 15:40:47  1 of 1 OK created view model iowa_staging.staging_sales......................... [OK in 5.82s]
[2022-03-24 15:40:47,561] {subprocess.py:89} INFO - 15:40:47
[2022-03-24 15:40:47,561] {subprocess.py:89} INFO - 15:40:47  Finished running 1 view model in 11.03s.
[2022-03-24 15:40:47,562] {subprocess.py:89} INFO - 15:40:47
[2022-03-24 15:40:47,562] {subprocess.py:89} INFO - 15:40:47  Completed successfully
[2022-03-24 15:40:47,562] {subprocess.py:89} INFO - 15:40:47
[2022-03-24 15:40:47,563] {subprocess.py:89} INFO - 15:40:47  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2022-03-24 15:40:48,267] {local_task_job.py:211} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2022-03-24 15:40:48,268] {process_utils.py:120} INFO - Sending Signals.SIGTERM to group 215. PIDs of all processes in the group: [216, 217, 230, 215]
[2022-03-24 15:40:48,269] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 215
[2022-03-24 15:40:48,269] {taskinstance.py:1413} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-03-24 15:40:48,269] {subprocess.py:99} INFO - Sending SIGTERM signal to process group
[2022-03-24 15:40:48,276] {process_utils.py:70} INFO - Process psutil.Process(pid=217, status='terminated', started='15:40:32') (217) terminated with exit code None
[2022-03-24 15:40:48,282] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/bash.py", line 178, in execute
    result = self.subprocess_hook.run_command(
  File "/usr/local/lib/python3.9/site-packages/airflow/hooks/subprocess.py", line 87, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1415, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-03-24 15:40:48,287] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=model.iowa.staging_sales, execution_date=20220324T154032, start_date=20220324T154033, end_date=20220324T154048
[2022-03-24 15:40:48,297] {standard_task_runner.py:89} ERROR - Failed to execute job 172 for task model.iowa.staging_sales
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/bash.py", line 178, in execute
    result = self.subprocess_hook.run_command(
  File "/usr/local/lib/python3.9/site-packages/airflow/hooks/subprocess.py", line 87, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1415, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-03-24 15:40:48,302] {process_utils.py:70} INFO - Process psutil.Process(pid=215, status='terminated', exitcode=1, started='15:40:32') (215) terminated with exit code 1
[2022-03-24 15:40:48,303] {process_utils.py:70} INFO - Process psutil.Process(pid=230, status='terminated', started='15:40:35') (230) terminated with exit code None
[2022-03-24 15:40:48,303] {process_utils.py:70} INFO - Process psutil.Process(pid=216, status='terminated', started='15:40:32') (216) terminated with exit code None
